import { useState, useEffect } from 'react';
import axios from 'axios';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend, BarChart, Bar, XAxis, YAxis } from 'recharts';
import { Users, ShieldCheck, RefreshCw } from 'lucide-react';
import { Badge, Button, GlassCard, KpiCard, ChartCard } from './ui/primitives';
import { API_URL } from '../config';

const COLORS = ['#9a9ee8', '#7090cc', '#9ba0b8', '#70a888', '#c09060', '#c07070'];
function Coverage({ dimension }) { return <p className="mt-3 text-xs text-gray-400 border-t border-white/10 pt-3">Coverage: <span className="text-gray-200">{dimension?.coverage ?? 0}%</span> of eligible users · confidence: <span className="text-gray-200">{Math.round((dimension?.confidence ?? 0) * 100)}%</span></p>; }
function Donut({ dimension }) { const buckets = dimension?.buckets || []; return <div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={buckets} dataKey="users" nameKey="label" cx="50%" cy="50%" innerRadius={48} outerRadius={84} paddingAngle={2}>{buckets.map((entry, index) => <Cell key={entry.label} fill={entry.label.includes('unknown') ? '#596072' : COLORS[index % COLORS.length]} />)}</Pie><Tooltip contentStyle={{ backgroundColor: '#161827', border: '1px solid #454965', borderRadius: '10px' }} /><Legend wrapperStyle={{ color: '#b9bdd2', fontSize: 11 }} /></PieChart></ResponsiveContainer></div>; }
function Bars({ dimension }) { const buckets = dimension?.buckets || []; return <div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={buckets} layout="vertical" margin={{ left: 20 }}><XAxis type="number" hide /><YAxis type="category" dataKey="label" width={145} tick={{ fill: '#b9bdd2', fontSize: 11 }} /><Tooltip contentStyle={{ backgroundColor: '#161827', border: '1px solid #454965', borderRadius: '10px' }} /><Bar dataKey="users" fill="#7090cc" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div>; }

export default function DemographicsView({ refreshKey = 0 }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true);
  const fetchDemographics = async () => { setLoading(true); try { setData((await axios.get(`${API_URL}/demographics?t=${Date.now()}`)).data); } catch (error) { console.error('Error fetching demographics:', error); } finally { setLoading(false); } };
  useEffect(() => { fetchDemographics(); }, [refreshKey]);
  return <div className="space-y-8" aria-busy={loading}>
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div className="netra-page-header mb-0"><span className="netra-page-eyebrow">Privacy-Safe Analysis</span><h1 className="netra-page-title">Audience <span>Demographics</span></h1><p className="netra-page-subtitle">K-anonymous aggregate signals only. No individual profile cards.</p></div><div className="flex items-center gap-2"><Badge variant="success"><ShieldCheck className="w-3.5 h-3.5" /> Aggregated · No PII</Badge><Button variant="secondary" loading={loading} onClick={fetchDemographics}><RefreshCw className={loading ? 'animate-spin' : ''} />Refresh</Button></div></div>
    {loading ? <GlassCard className="p-12 text-center flex flex-col items-center justify-center gap-3"><RefreshCw className="w-8 h-8 text-indigo-400 animate-spin" /><p className="text-gray-300 font-medium">Preparing aggregate demographic summary…</p></GlassCard> : !data ? <GlassCard className="p-12 text-center"><Users className="w-8 h-8 text-gray-500 mx-auto mb-2" /><h2 className="text-lg font-semibold text-gray-200">No demographic data available</h2><p className="text-gray-400 text-sm">Waiting for enough public signals to form anonymous groups.</p></GlassCard> : <>
      <div className="netra-grid-12"><div className="col-span-12 md:col-span-6 lg:col-span-3"><KpiCard label="Users in Aggregate" value={data.total_users} delta="Sample" deltaType="positive" subtext="No profiles retained" /></div><div className="col-span-12 md:col-span-6 lg:col-span-3"><KpiCard label="Geographic Coverage" value={`${data.geography?.coverage || 0}%`} delta="Country/state only" deltaType="neutral" subtext="Public location signal" /></div><div className="col-span-12 md:col-span-6 lg:col-span-3"><KpiCard label="Interest Coverage" value={`${data.interests?.coverage || 0}%`} delta="Fixed taxonomy" deltaType="neutral" subtext="Bio/content signals" /></div><div className="col-span-12 md:col-span-6 lg:col-span-3"><KpiCard label="Age Coverage" value={`${data.age?.coverage || 0}%`} delta="Explicit cues only" deltaType="positive" subtext={`${data.age?.excluded_minors || 0} minors excluded`} /></div></div>
      <div className="netra-grid-12"><div className="col-span-12 lg:col-span-6"><ChartCard title="Professional Interests" subtitle="Fixed taxonomy; aggregate-only"><Donut dimension={data.interests} /><Coverage dimension={data.interests} /></ChartCard></div><div className="col-span-12 lg:col-span-6"><ChartCard title="Linguistic Spread" subtitle="Post and bio language signals"><Donut dimension={data.language} /><Coverage dimension={data.language} /></ChartCard></div><div className="col-span-12 lg:col-span-6"><ChartCard title="Geography" subtitle="Map-style country/state distribution; no precise location"><Bars dimension={data.geography} /><Coverage dimension={data.geography} /></ChartCard></div><div className="col-span-12 lg:col-span-6"><ChartCard title="Age Brackets" subtitle="Explicit self-stated ages only; minors excluded"><Bars dimension={data.age} /><Coverage dimension={data.age} /></ChartCard></div><div className="col-span-12"><ChartCard title="Activity Patterns" subtitle="Posting level and reply/original ratio"><Bars dimension={data.activity_patterns} /><Coverage dimension={data.activity_patterns} /></ChartCard></div><div className="col-span-12"><GlassCard className="p-5 text-sm text-gray-300"><ShieldCheck className="inline w-4 h-4 mr-2 text-emerald-300" />{data.privacy_note}</GlassCard></div></div>
    </>}
  </div>;
}
