import { useEffect, useState } from 'react';
import axios from 'axios';
import { API_URL } from '../config';

const hints = { LIVE: 'Connected and collecting authorized content.', CREDENTIALS_REQUIRED: 'Set or renew the Meta Page/system-user token in .env.', PERMISSION_REQUIRED: 'Grant the required Page or Instagram Graph permissions to the system user.', RATE_LIMITED: 'Meta is temporarily throttling requests; the scheduler will retry.', DEGRADED: 'Check the connection details and retry the sync.', DISABLED: 'This collector is not enabled in this build.' };
const relativeTime = value => { if (!value) return 'Not yet'; const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); return seconds < 60 ? 'just now' : seconds < 3600 ? `${Math.floor(seconds / 60)}m ago` : `${Math.floor(seconds / 3600)}h ago`; };
const until = value => { if (!value) return 'Not scheduled'; const seconds = Math.max(0, Math.floor((new Date(value).getTime() - Date.now()) / 1000)); return seconds < 60 ? `in ${seconds}s` : `in ${Math.ceil(seconds / 60)}m`; };
const shortId = value => value ? `${String(value).slice(0, 12)}…` : 'masked';

export default function MetaFeedView() {
  const [items, setItems] = useState([]); const [sources, setSources] = useState({}); const [busy, setBusy] = useState({});
  const load = async () => { const [feed, health] = await Promise.all([axios.get(`${API_URL}/meta/feed?limit=60`), axios.get(`${API_URL}/health/sources`)]); setItems(feed.data.items || []); setSources(health.data || {}); };
  useEffect(() => { load().catch(() => {}); const id = setInterval(() => load().catch(() => {}), 15000); return () => clearInterval(id); }, []);
  const sync = async platform => { setBusy(value => ({ ...value, [platform]: true })); try { await axios.post(`${API_URL}/meta/sync?platform=${platform}`); await load(); } finally { setBusy(value => ({ ...value, [platform]: false })); } };
  return <div className="space-y-5"><h1 className="text-xl font-light text-white">Meta <span className="text-indigo-300 font-normal">Feed</span></h1><div className="grid md:grid-cols-2 gap-3">{['facebook', 'instagram'].map(platform => { const source = sources[platform] || {}; const status = source.status || 'READY'; return <article className="glass p-4" key={platform}><div className="flex justify-between gap-3"><span className="capitalize text-white">{platform}</span><span className="pill text-[10px]">{status}</span></div><p className="text-xs text-slate-300 mt-2">{source.message || hints[status] || 'Ready to collect.'}</p>{source.reason && <p className="text-[10px] text-amber-200 mt-1">Reason: {source.reason}</p>}<p className="text-[10px] text-slate-500 mt-2">How to fix: {hints[status] || 'Use Sync now to check the connection.'}</p><div className="grid grid-cols-2 gap-1 mt-3 text-[10px] text-slate-500"><span>Route: {source.route || 'Not reported'}</span><span>Token expiry: {source.token_expires_at || 'Not reported'}</span><span>Last synced: {relativeTime(source.last_success)}</span><span>Next run: {until(source.next_run_at)}</span></div><div className="mt-3 flex justify-between gap-2 text-[10px] text-slate-500"><span>{source.api_usage ? `Meta API usage: ${source.api_usage}` : 'Meta API usage not reported'}</span><button className="pill text-[10px]" onClick={() => sync(platform)} disabled={busy[platform]}>{busy[platform] ? 'Syncing...' : 'Sync now'}</button></div></article>; })}</div><div className="space-y-2">{!items.length && <div className="glass p-5 text-sm text-slate-400">Connected, no content yet. Publish a post and a comment on your Page/Instagram, then press Sync now.</div>}{items.map(item => <article className="glass p-4" key={item.canonical_id}><div className="flex gap-2 text-[10px]"><span className="pill">{item.platform}</span><span className={item.source_mode === 'LIVE' ? 'text-emerald-300' : 'text-slate-400'}>{item.source_mode || 'UNKNOWN'}</span><span className="text-slate-500">{item.event_type} · {relativeTime(item.created_at || item.ingested_at)}</span></div><p className="text-sm text-slate-200 mt-2 whitespace-pre-wrap">{item.text || '(no text)'}</p><div className="text-[10px] text-slate-500 mt-2">author {shortId(item.author_id)} · likes {item.metrics?.likes || 0}</div>{item.url && <a className="text-xs text-indigo-300" href={item.url} target="_blank" rel="noreferrer">Open permalink</a>}</article>)}</div></div>;
}
