import { useEffect, useState } from 'react';
import axios from 'axios';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { RefreshCw, TrendingUp } from 'lucide-react';
import { API_URL } from '../config';
import { Badge, Button, ChartCard, GlassCard } from './ui/primitives';

const tone = { VIRAL: 'danger', RISING: 'success', EMERGING: 'accent', STABLE: 'neutral', DECLINING: 'warning' };
export default function TrendsView({ refreshKey = 0 }) {
  const [trends, setTrends] = useState([]), [active, setActive] = useState(null), [at, setAt] = useState(''), [loading, setLoading] = useState(true);
  const load = async (replay = at) => { setLoading(true); try { const url = replay ? `${API_URL}/trends/replay?at=${encodeURIComponent(replay)}` : `${API_URL}/trends/rising`; const data = (await axios.get(url)).data; setTrends(data.trends || []); setActive((data.trends || [])[0] || null); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [refreshKey]);
  const detail = async (trend) => { setActive(trend); try { const evidence = (await axios.get(`${API_URL}/trends/${trend.narrative_id}/evidence`)).data; setActive({ ...trend, evidence }); } catch (_) {} };
  return <div className="space-y-6"><div className="netra-page-header flex flex-wrap items-end justify-between gap-3"><div><span className="netra-page-eyebrow">Replayable trend intelligence</span><h1 className="netra-page-title">Rising <span>Topics</span></h1><p className="netra-page-subtitle">Six-hour rolling windows, relative to the collected dataset timeline.</p></div><div className="flex gap-2"><input className="bg-white/5 border border-white/15 rounded px-3 py-2 text-sm" aria-label="Replay timestamp" placeholder="Replay ISO timestamp" value={at} onChange={e => setAt(e.target.value)} /><Button variant="secondary" onClick={() => load()} loading={loading}><RefreshCw />Refresh</Button></div></div>
    <div className="grid grid-cols-1 xl:grid-cols-5 gap-5"><GlassCard className="xl:col-span-2 p-4"><h2 className="text-sm font-semibold text-white mb-3">Trending list</h2>{!trends.length ? <p className="text-sm text-slate-400">No topics in this replay window.</p> : <div className="space-y-2">{trends.map(t => <button key={t.narrative_id} onClick={() => detail(t)} className="w-full text-left p-3 rounded-lg hover:bg-white/5 border border-white/5"><div className="flex justify-between gap-2"><strong className="text-sm text-white truncate">{t.label}</strong><Badge variant={tone[t.status]}>{t.status}</Badge></div><div className="flex justify-between mt-2 text-xs text-slate-400"><span>{t.growth_percent > 0 ? '+' : ''}{t.growth_percent}% growth</span><span>score {t.score}</span><span>↗ {Math.round(t.forecast?.likely_to_go_viral * 100 || 0)}%</span></div></button>)}</div>}</GlassCard>
      <div className="xl:col-span-3 space-y-5">{active ? <><ChartCard title={active.label} subtitle={`${active.status} · forecast arrow = likely viral probability`}><div className="h-56"><ResponsiveContainer><AreaChart data={active.timeline || []}><XAxis dataKey="bucket" hide /><YAxis /><Tooltip /><Area dataKey="volume" stroke="#9a9ee8" fill="#9a9ee844" /></AreaChart></ResponsiveContainer></div><div className="grid grid-cols-2 md:grid-cols-3 gap-2 text-xs text-slate-300 mt-3">{Object.entries(active.score_components || {}).map(([k,v]) => <span key={k} className="bg-white/5 rounded p-2">{k.replace('_',' ')}: {Math.round(v*100)}%</span>)}</div></ChartCard><GlassCard className="p-5"><h2 className="text-sm font-semibold text-white">Evidence</h2><p className="text-xs text-slate-400 mt-1">{active.evidence?.wording || 'earliest observed in our collected dataset'}</p><p className="text-xs text-slate-300 mt-3">Platform mix: {Object.entries(active.evidence?.platform_mix || active.platform_mix || {}).map(([k,v]) => `${k} ${v}`).join(' · ')}</p><p className="text-xs text-slate-300 mt-2">Sentiment shift: {active.evidence?.sentiment_shift ?? 'pending'}</p><div className="mt-3 space-y-2">{(active.evidence?.posts || []).slice(0,3).map((p,i) => <p key={p.post_id || i} className="text-xs text-slate-300 border-t border-white/10 pt-2">{p.text || p.text_content}</p>)}</div></GlassCard></> : <GlassCard className="p-10 text-center text-slate-400"><TrendingUp className="mx-auto mb-2" />Select a trend to inspect it.</GlassCard>}</div></div></div>;
}
